version: "2.2"

services:
  elasticsearch:
    image: elasticsearch:5.6
    restart: always
    cpus: 1
    mem_limit: 2G
    environment:
      - TZ=Asia/Shanghai
    # ports:
    # - "9200:9200"
    # - "9300:9300"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data
  server:
    # run "sh build-docker-server-image.sh" to build the image
    image: easy-es-server:1.0.0
    cpus: 0.5
    mem_limit: 1G
    restart: always
    volumes:
      - ./volumes/server/configs.js:/app/configs.js
    ports:
      - "80:80"
    links:
      - elasticsearch
  # [kibana] if you need :)
  # kibana:
  #   image: kibana:5.6
  #   cpus: 0.5
  #   mem_limit: 500m
  #   restart: always
  #   ports:
  #     - "5601:5601"
  #   links:
  #     - elasticsearch
