version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:5.6
    restart: always
    cpus: 1
    mem_limit: 2G
    environment:
     - TZ=Asia/Shanghai
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - ./volumes/es:/usr/share/elasticsearch/data

  kibana:
    image: kibana:5.6
    cpus: 0.5
    mem_limit: 500m
    restart: always
    ports:
     - "5601:5601"
    links:
     - elasticsearch